version: '3.8'

services:
  atendimento:
    ports:
      - 8081:8081
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=jdbc:mysql://mysql:3306/atendimento
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin123
